name: GitHub Actions Creating_dependent_jobs
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: ./setup_server.sh
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ./build_server.sh
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ./test_server.sh
